// <auto-generated />
namespace EntityClasses.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Initilization11 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Initilization11));
        
        string IMigrationMetadata.Id
        {
            get { return "201801140917093_Initilization11"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
